"""API 序列化器模块"""
# 从现有的 api_serializers.py 中导入所有序列化器
from ...api_serializers import (
    # 基础读取序列化器
    DepartmentSerializer,
    PositionSerializer,
    UserSerializer,
    EmployeeSerializer,
    AttendanceSerializer,
    LeaveRequestSerializer,
    SalaryRecordSerializer,
    SystemLogSerializer,
    RBACPermissionSerializer,
    RoleSerializer,
    CompanyDocumentSerializer,
    BusinessTripSerializer,
    TravelExpenseSerializer,
    CheckInLocationSerializer,
    
    # 写入序列化器
    DepartmentWriteSerializer,
    PositionWriteSerializer,
    EmployeeWriteSerializer,
    AttendanceWriteSerializer,
    LeaveRequestWriteSerializer,
    LeaveApproveSerializer,
    SalaryRecordWriteSerializer,
    ChangePasswordSerializer,
    AdminResetPasswordSerializer,
    UserProfileUpdateSerializer,
    CompanyDocumentWriteSerializer,
    RBACPermissionWriteSerializer,
    RoleWriteSerializer,
    UserWriteSerializer,
    BusinessTripWriteSerializer,
    TravelExpenseWriteSerializer,
    CheckInLocationWriteSerializer,
)

# 优化版序列化器（轻量级，用于列表）
from .optimized import (
    DepartmentLiteSerializer,
    PositionLiteSerializer,
    UserLiteSerializer,
    EmployeeLiteSerializer,
    AttendanceListSerializer,
    LeaveListSerializer,
    SalaryListSerializer,
    SupplementListSerializer,
    BusinessTripListSerializer,
    TravelExpenseListSerializer,
    BulkIdSerializer,
    BulkApproveSerializer,
)

__all__ = [
    # Read
    'DepartmentSerializer',
    'PositionSerializer',
    'UserSerializer',
    'EmployeeSerializer',
    'AttendanceSerializer',
    'LeaveRequestSerializer',
    'SalaryRecordSerializer',
    'SystemLogSerializer',
    'RBACPermissionSerializer',
    'RoleSerializer',
    'CompanyDocumentSerializer',
    'BusinessTripSerializer',
    'TravelExpenseSerializer',
    'CheckInLocationSerializer',
    # Write
    'DepartmentWriteSerializer',
    'PositionWriteSerializer',
    'EmployeeWriteSerializer',
    'AttendanceWriteSerializer',
    'LeaveRequestWriteSerializer',
    'LeaveApproveSerializer',
    'SalaryRecordWriteSerializer',
    'ChangePasswordSerializer',
    'AdminResetPasswordSerializer',
    'UserProfileUpdateSerializer',
    'CompanyDocumentWriteSerializer',
    'RBACPermissionWriteSerializer',
    'RoleWriteSerializer',
    'UserWriteSerializer',
    'BusinessTripWriteSerializer',
    'TravelExpenseWriteSerializer',
    'CheckInLocationWriteSerializer',
    # Optimized (Lite/List)
    'DepartmentLiteSerializer',
    'PositionLiteSerializer',
    'UserLiteSerializer',
    'EmployeeLiteSerializer',
    'AttendanceListSerializer',
    'LeaveListSerializer',
    'SalaryListSerializer',
    'SupplementListSerializer',
    'BusinessTripListSerializer',
    'TravelExpenseListSerializer',
    'BulkIdSerializer',
    'BulkApproveSerializer',
]
