# Generated by Django 4.2.7 on 2025-10-23 09:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('description', models.TextField(blank=True, verbose_name='部门描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='员工编号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(verbose_name='地址')),
                ('id_card', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='请输入有效的身份证号码', regex='^\\d{17}[\\dXx]$')], verbose_name='身份证号')),
                ('marital_status', models.CharField(choices=[('single', '未婚'), ('married', '已婚'), ('divorced', '离婚'), ('widowed', '丧偶')], default='single', max_length=10, verbose_name='婚姻状况')),
                ('emergency_contact', models.CharField(max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(max_length=20, verbose_name='紧急联系电话')),
                ('hire_date', models.DateField(verbose_name='入职日期')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基本工资')),
                ('is_active', models.BooleanField(default=True, verbose_name='在职状态')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_management.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='职位名称')),
                ('description', models.TextField(blank=True, verbose_name='职位描述')),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最低薪资')),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高薪资')),
                ('requirements', models.TextField(blank=True, verbose_name='任职要求')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', '病假'), ('personal', '事假'), ('annual', '年假'), ('maternity', '产假'), ('paternity', '陪产假'), ('other', '其他')], max_length=20, verbose_name='请假类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('days', models.IntegerField(verbose_name='请假天数')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('comments', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_management.position', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账户'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hr_management.employee', verbose_name='部门经理'),
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基本工资')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='奖金')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='加班费')),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='津贴')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='扣款')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实发工资')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '薪资记录',
                'verbose_name_plural': '薪资记录',
                'ordering': ['-year', '-month', 'employee'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='上班时间')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='下班时间')),
                ('attendance_type', models.CharField(choices=[('check_in', '上班打卡'), ('check_out', '下班打卡'), ('late', '迟到'), ('early_leave', '早退'), ('absent', '缺勤'), ('leave', '请假')], default='check_in', max_length=20, verbose_name='考勤类型')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
