# Generated by Django 4.2.7 on 2025-10-24 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='departments/', verbose_name='部门图标'),
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='documents/contracts/', verbose_name='合同'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_card_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_cards/', verbose_name='身份证复印件'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='documents/resumes/', verbose_name='简历'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='documents/leave_attachments/', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='照片'),
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('document_type', models.CharField(choices=[('policy', '政策文件'), ('procedure', '流程文件'), ('template', '模板文件'), ('announcement', '公告通知'), ('training', '培训资料'), ('other', '其他')], max_length=20, verbose_name='文档类型')),
                ('description', models.TextField(blank=True, verbose_name='文档描述')),
                ('file', models.FileField(upload_to='documents/company/', verbose_name='文档文件')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '公司文档',
                'verbose_name_plural': '公司文档',
                'ordering': ['-created_at'],
            },
        ),
    ]
