# Generated by Django 4.2.7 on 2025-10-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0002_department_icon_employee_avatar_employee_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
