# Generated by Django 4.2.7 on 2025-10-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0005_rbacpermission_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='首次登录需改密码'),
        ),
    ]
