# Generated by Django 4.2.7 on 2025-10-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0007_alter_employee_address_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('code_type', models.CharField(choices=[('reset_password', '重置密码'), ('register', '注册验证'), ('login', '登录验证')], default='reset_password', max_length=20, verbose_name='验证码类型')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'code_type', '-created_at'], name='hr_manageme_phone_9751a8_idx')],
            },
        ),
    ]
