# Generated by Django 4.2.7 on 2025-11-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0008_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='已发薪'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发薪时间'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', '病假'), ('personal', '事假'), ('annual', '年假'), ('maternity', '产假'), ('paternity', '陪产假'), ('other', '其他'), ('resignation', '离职申请')], max_length=20, verbose_name='请假类型'),
        ),
    ]
