# Generated by Django 4.2.7 on 2025-12-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0010_leaverequest_resignation_flow'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'attendance_type'], name='hr_manageme_date_c379c4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', '-date'], name='hr_manageme_employe_768938_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', '-created_at'], name='hr_manageme_status_6f411a_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'leave_type', 'status'], name='hr_manageme_employe_0bd782_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['level', '-timestamp'], name='hr_manageme_level_dbbe70_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['-timestamp'], name='hr_manageme_timesta_6c38f4_idx'),
        ),
    ]
