# Generated by Django 4.2.7 on 2026-01-16 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_management', '0011_add_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rbacpermission',
            options={'ordering': ['id'], 'verbose_name': 'RBAC权限', 'verbose_name_plural': 'RBAC权限'},
        ),
        migrations.CreateModel(
            name='AttendanceSupplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='补签日期')),
                ('time', models.TimeField(verbose_name='补签时间')),
                ('supplement_type', models.CharField(choices=[('check_in', '补签到'), ('check_out', '补签退')], max_length=20, verbose_name='补签类型')),
                ('reason', models.TextField(verbose_name='补签原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('comments', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '补签申请',
                'verbose_name_plural': '补签申请',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='hr_manageme_status_ec709f_idx'), models.Index(fields=['employee', '-created_at'], name='hr_manageme_employe_139250_idx')],
            },
        ),
    ]
