# Generated by Django 4.2.7 on 2026-01-16 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_management', '0012_add_attendance_supplement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200, verbose_name='出差地点')),
                ('trip_type', models.CharField(choices=[('domestic', '国内出差'), ('overseas', '海外出差')], default='domestic', max_length=20, verbose_name='出差类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('days', models.IntegerField(verbose_name='出差天数')),
                ('reason', models.TextField(verbose_name='出差事由')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('comments', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '出差申请',
                'verbose_name_plural': '出差申请',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='hr_manageme_status_f326b4_idx'), models.Index(fields=['employee', '-created_at'], name='hr_manageme_employe_5951c8_idx')],
            },
        ),
    ]
