# Generated by Django 4.2.7 on 2026-01-16 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_management', '0013_businesstrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('travel', '差旅费'), ('transport', '交通费'), ('accommodation', '住宿费'), ('meal', '餐饮费'), ('other', '其他')], default='travel', max_length=20, verbose_name='报销类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='报销金额')),
                ('description', models.TextField(verbose_name='报销事由')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('paid', '已报销')], default='pending', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('comments', models.TextField(blank=True, verbose_name='审批意见')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='报销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('business_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='hr_management.businesstrip', verbose_name='关联出差')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '差旅报销',
                'verbose_name_plural': '差旅报销',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='hr_manageme_status_365820_idx'), models.Index(fields=['employee', '-created_at'], name='hr_manageme_employe_71bb2d_idx')],
            },
        ),
    ]
