# Generated by Django 4.2.7 on 2026-01-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0014_travelexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelexpense',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='发票文件'),
        ),
    ]
