# Generated by Django 4.2.7 on 2026-01-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0015_add_invoice_to_travel_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_departments', to='hr_management.employee', verbose_name='部门主管'),
        ),
    ]
