# Generated by Django 4.2.7 on 2026-01-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0017_add_department_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrecord',
            name='deduction',
        ),
    ]
