# Generated by Django 4.2.7 on 2026-01-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0018_remove_deduction_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地点名称')),
                ('address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='经度')),
                ('radius', models.IntegerField(default=1000, verbose_name='允许范围(米)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认签到点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '签到地点',
                'verbose_name_plural': '签到地点',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
