# Generated by Django 4.2.7 on 2026-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0019_add_checkin_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='checkin_locations',
            field=models.ManyToManyField(blank=True, related_name='employees', to='hr_management.checkinlocation', verbose_name='关联考勤地点'),
        ),
    ]
