# Generated by Django 4.2.7 on 2026-01-24 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_management', '0020_add_employee_checkin_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboard_reject_reason',
            field=models.TextField(blank=True, verbose_name='入职拒绝原因'),
        ),
        migrations.AddField(
            model_name='employee',
            name='onboard_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入职审核时间'),
        ),
        migrations.AddField(
            model_name='employee',
            name='onboard_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employees', to=settings.AUTH_USER_MODEL, verbose_name='入职审核人'),
        ),
        migrations.AddField(
            model_name='employee',
            name='onboard_status',
            field=models.CharField(choices=[('pending', '待入职'), ('onboarded', '已入职'), ('resigned', '已离职')], default='onboarded', max_length=20, verbose_name='入职状态'),
        ),
    ]
