# Generated by Django 4.2.7 on 2026-01-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0021_add_onboard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_card_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='工资卡银行账号'),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, verbose_name='血型'),
        ),
        migrations.AddField(
            model_name='employee',
            name='computer_brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='电脑品牌'),
        ),
        migrations.AddField(
            model_name='employee',
            name='computer_info',
            field=models.CharField(blank=True, max_length=20, verbose_name='电脑信息'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, max_length=20, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=20, verbose_name='与本人关系'),
        ),
        migrations.AddField(
            model_name='employee',
            name='english_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='英文名'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ethnicity',
            field=models.CharField(blank=True, default='汉族', max_length=20, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='employee',
            name='expense_card_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='报销卡银行账号'),
        ),
        migrations.AddField(
            model_name='employee',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='毕业时间'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hukou_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='户籍地址'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hukou_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='户籍所在地'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hukou_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='户籍性质'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='documents/id_cards/', verbose_name='身份证国徽面'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='documents/id_cards/', verbose_name='身份证人像面'),
        ),
        migrations.AddField(
            model_name='employee',
            name='major',
            field=models.CharField(blank=True, max_length=100, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, default='中国', max_length=50, verbose_name='国籍'),
        ),
        migrations.AddField(
            model_name='employee',
            name='native_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='籍贯'),
        ),
        migrations.AddField(
            model_name='employee',
            name='party_date',
            field=models.DateField(blank=True, null=True, verbose_name='入党/团日期'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='护照号码'),
        ),
        migrations.AddField(
            model_name='employee',
            name='political_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='政治面貌'),
        ),
        migrations.AddField(
            model_name='employee',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='毕业学校名称'),
        ),
        migrations.AddField(
            model_name='employee',
            name='school_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='学校分类'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, verbose_name='联系地址'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像照片'),
        ),
    ]
