# Generated by Django 4.2.7 on 2026-01-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0022_add_employee_extended_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_card_copy',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='resume',
        ),
    ]
