# Generated by Django 4.2.7 on 2026-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0023_remove_employee_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='default_roles',
            field=models.ManyToManyField(blank=True, related_name='positions', to='hr_management.role', verbose_name='默认角色'),
        ),
    ]
