# Generated by Django 4.2.7 on 2026-01-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0024_add_position_default_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='passport_no',
        ),
    ]
